import { WeatherValuesNames } from './values.types'

export const weatherValuesNames: WeatherValuesNames = {
    cloud: 'Cloudiness',
    condition: 'Condition',
    feelslike_c: 'Feels like',
    feelslike_f: 'feelslike_f',
    gust_kph: 'Gust',
    gust_mph: 'Gust',
    humidity: 'Humidity',
    last_updated: 'Last updated',
    last_updated_epoch: 'Last updated',
    precip_in: 'Precipitation',
    precip_mm: 'Precipitation',
    pressure_in: 'Pressure',
    pressure_mb: 'Pressure',
    temp_c: 'Temperature',
    temp_f: 'Temperature',
    uv: 'UV index',
    vis_km: 'Visibility',
    vis_miles: 'Visibility',
    wind_degree: 'Wind direction',
    wind_dir: 'Wind direction',
    wind_kph: 'Wind speed',
    wind_mph: 'Wind speed',
}
